# Dependencies
markdown:         
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dang Lien Minh
tagline:          'Dang Lien Minh'
description:      ''
url:              
baseurl:          /

author:
  name:           'Noor'
  url:            
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:         
  collections:
  photos:
    output: true

 